//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TileEdit.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class en_US {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal en_US() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TileEdit.Properties.en-US", typeof(en_US).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Cancel.
        /// </summary>
        internal static string CancelButton {
            get {
                return ResourceManager.GetString("CancelButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to en.
        /// </summary>
        internal static string CountryCode {
            get {
                return ResourceManager.GetString("CountryCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English.
        /// </summary>
        internal static string EnglishName {
            get {
                return ResourceManager.GetString("EnglishName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E_xit.
        /// </summary>
        internal static string ExitMenuItem {
            get {
                return ResourceManager.GetString("ExitMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _File.
        /// </summary>
        internal static string FileMenuItem {
            get {
                return ResourceManager.GetString("FileMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fixed Size.
        /// </summary>
        internal static string FixedSize {
            get {
                return ResourceManager.GetString("FixedSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to en-US.
        /// </summary>
        internal static string FullCountryCode {
            get {
                return ResourceManager.GetString("FullCountryCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 8-bit Grayscale.
        /// </summary>
        internal static string Gray8Bit {
            get {
                return ResourceManager.GetString("Gray8Bit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AmericanEnglish.
        /// </summary>
        internal static string Identifier {
            get {
                return ResourceManager.GetString("Identifier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Indexed 8-bit, 6 bits per channel (VGA).
        /// </summary>
        internal static string Indexed6Bit {
            get {
                return ResourceManager.GetString("Indexed6Bit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Indexed 8-bit, 8 bits per channel.
        /// </summary>
        internal static string Indexed8Bit {
            get {
                return ResourceManager.GetString("Indexed8Bit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _New Tileset.
        /// </summary>
        internal static string NewMenuItem {
            get {
                return ResourceManager.GetString("NewMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Tileset.
        /// </summary>
        internal static string NewTilesetDialogTitle {
            get {
                return ResourceManager.GetString("NewTilesetDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Ok.
        /// </summary>
        internal static string OkButton {
            get {
                return ResourceManager.GetString("OkButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Open....
        /// </summary>
        internal static string OpenMenuItem {
            get {
                return ResourceManager.GetString("OpenMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pixel Format.
        /// </summary>
        internal static string PixelFormat {
            get {
                return ResourceManager.GetString("PixelFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AmericanEnglish.
        /// </summary>
        internal static string QualifiedEnglishName {
            get {
                return ResourceManager.GetString("QualifiedEnglishName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to American English.
        /// </summary>
        internal static string QualifiedTranslatedName {
            get {
                return ResourceManager.GetString("QualifiedTranslatedName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 16-bit RGBA, 4 bits per channel.
        /// </summary>
        internal static string Rgba16Bit {
            get {
                return ResourceManager.GetString("Rgba16Bit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 32-bit RGBA, 8 bits per channel.
        /// </summary>
        internal static string Rgba8Bit {
            get {
                return ResourceManager.GetString("Rgba8Bit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Translated Phrase.
        /// </summary>
        internal static string TestTranslationPhrase {
            get {
                return ResourceManager.GetString("TestTranslationPhrase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Height.
        /// </summary>
        internal static string TilesetHeight {
            get {
                return ResourceManager.GetString("TilesetHeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tileset Type.
        /// </summary>
        internal static string TilesetType {
            get {
                return ResourceManager.GetString("TilesetType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Width.
        /// </summary>
        internal static string TilesetWidth {
            get {
                return ResourceManager.GetString("TilesetWidth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tile Size.
        /// </summary>
        internal static string TileSize {
            get {
                return ResourceManager.GetString("TileSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English.
        /// </summary>
        internal static string TranslatedName {
            get {
                return ResourceManager.GetString("TranslatedName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Variable Size.
        /// </summary>
        internal static string VariableSize {
            get {
                return ResourceManager.GetString("VariableSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to X.
        /// </summary>
        internal static string X {
            get {
                return ResourceManager.GetString("X", resourceCulture);
            }
        }
    }
}
